%load_ext autoreload
%autoreload 2
from tools.ramanflow.read_data import ReadData as rd
x_data, uv_data_04_26 = rd.read_data('data/20210427 MG ACE ACETAMIPRID colloidal SERS3/20210426_batch2_4X.txt')
x_data, uv_data_04_26_batch2 = rd.read_data('data/20210427 MG ACE ACETAMIPRID colloidal SERS3/20210426_batch2_4X.txt')
x_data, uv_data_04_26_batch3 = rd.read_data('data/20210427 MG ACE ACETAMIPRID colloidal SERS3/20210426_batch3_4X.txt')
x_data_0426, uv_data_04_26_batch3 = rd.read_data('data/20210427 MG ACE ACETAMIPRID colloidal SERS3/20210426_batch3_4X.txt')
x_data_0706, uv_data_07_06 = rd.read_data('data/20210707 colloidal SERS multiple analytes/20210706_batch_4X.txt')
x_data_0810, uv_data_08_10_5X = rd.read_data('data/20210810 SERS timed immersion experiment/20210809_colloids_5Xdilute.txt')
x_data_1029, uv_data_20sec = rd.read_data('data/20211029 multiple colloidal SERS test/absorbance/20_sec_1_to_4_colloids.txt')
x_data_1029, uv_data_30sec = rd.read_data('data/20211029 multiple colloidal SERS test/absorbance/30_sec_1_to_4_colloids.txt')
x_data_1029, uv_data_1min = rd.read_data('data/20211029 multiple colloidal SERS test/absorbance/1_min_1_to_4_colloids.txt')
x_data_1029, uv_data_2min = rd.read_data('data/20211029 multiple colloidal SERS test/absorbance/2_min_1_to_4_colloids.txt')
x_data_1029, uv_data_3min = rd.read_data('data/20211029 multiple colloidal SERS test/absorbance/3_min_1_to_4_colloids.txt')
x_data_1029, uv_data_10min = rd.read_data('data/20211029 multiple colloidal SERS test/absorbance/10_min_1_to_4_colloids.txt')
import matplotlib.pyplot as plt
path = 'data/20211029 multiple colloidal SERS test/'
f_sup, car_20sec = rd.read_data(path + '1_new/1_0s_aftermixing_20_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
car_20sec_mean = np.mean(car_20sec, axis=0)
plt.plot(f_sup, car_20sec_mean)
f_sup, car_30sec = rd.read_data(path + '1_new/1_0s_aftermixing_30_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
car_30sec_mean = np.mean(car_30sec, axis=0)
f_sup, car_1min = rd.read_data(path + '1_new/1_0s_aftermixing_1_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
car_1min_mean = np.mean(car_1min, axis=0)
f_sup, car_2min = rd.read_data(path + '1_new/1_0s_aftermixing_2_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
car_2min_mean = np.mean(car_2min, axis=0)
f_sup, car_3min = rd.read_data(path + '1_new/1_0s_aftermixing_3_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
f_sup, car_10min = rd.read_data(path + '1_new/1_0s_aftermixing_10_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
car_3min_mean = np.mean(car_3min, axis=0)
car_10min_mean = np.mean(car_10min, axis=0)
f_sup, aceta_20sec = rd.read_data(path + '4/4_20_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceta_20sec_mean = np.mean(aceta_20sec, axis=0)
f_sup, aceta_30sec = rd.read_data(path + '4/4_20_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceta_30sec_mean = np.mean(aceta_30sec, axis=0)
f_sup, aceta_1min = rd.read_data(path + '4/4_20_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceta_1min_mean = np.mean(aceta_1min, axis=0)
f_sup, aceta_2min = rd.read_data(path + '4/4_20_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceta_2min_mean = np.mean(aceta_2min, axis=0)
f_sup, aceta_3min = rd.read_data(path + '4/4_20_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
f_sup, aceta_10min = rd.read_data(path + '4/4_20_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceta_3min_mean = np.mean(aceta_3min, axis=0)
aceta_10min_mean = np.mean(aceta_10min, axis=0)
f_sup, aceta_20sec = rd.read_data(path + '4/4_20_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceta_20sec_mean = np.mean(aceta_20sec, axis=0)
f_sup, aceta_30sec = rd.read_data(path + '4/4_30_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceta_30sec_mean = np.mean(aceta_30sec, axis=0)
f_sup, aceta_1min = rd.read_data(path + '4/4_1_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceta_1min_mean = np.mean(aceta_1min, axis=0)
f_sup, aceta_2min = rd.read_data(path + '4/4_2_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceta_2min_mean = np.mean(aceta_2min, axis=0)
f_sup, aceta_3min = rd.read_data(path + '4/4_3_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
f_sup, aceta_10min = rd.read_data(path + '4/4_10_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceta_3min_mean = np.mean(aceta_3min, axis=0)
aceta_10min_mean = np.mean(aceta_10min, axis=0)
f_sup, aceph_20sec = rd.read_data(path + '5/5_20_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceph_20sec_mean = np.mean(aceph_20sec, axis=0)
f_sup, aceph_30sec = rd.read_data(path + '5/5_30_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceph_30sec_mean = np.mean(aceph_30sec, axis=0)
f_sup, aceph_1min = rd.read_data(path + '5/5_1_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceph_1min_mean = np.mean(aceph_1min, axis=0)
f_sup, aceph_2min = rd.read_data(path + '5/5_2_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceph_2min_mean = np.mean(aceph_2min, axis=0)
f_sup, aceph_3min = rd.read_data(path + '5/5_3_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
f_sup, aceph_10min = rd.read_data(path + '5/5_10_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceph_3min_mean = np.mean(aceph_3min, axis=0)
aceph_10min_mean = np.mean(aceph_10min, axis=0)
import numpy as np
path = 'data/20211029 multiple colloidal SERS test/'
f_sup, car_20sec = rd.read_data(path + '1_new/1_0s_aftermixing_20_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
car_20sec_mean = np.mean(car_20sec, axis=0)
plt.plot(f_sup, car_20sec_mean)
f_sup, car_30sec = rd.read_data(path + '1_new/1_0s_aftermixing_30_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
car_30sec_mean = np.mean(car_30sec, axis=0)
f_sup, car_1min = rd.read_data(path + '1_new/1_0s_aftermixing_1_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
car_1min_mean = np.mean(car_1min, axis=0)
f_sup, car_2min = rd.read_data(path + '1_new/1_0s_aftermixing_2_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
car_2min_mean = np.mean(car_2min, axis=0)
f_sup, car_3min = rd.read_data(path + '1_new/1_0s_aftermixing_3_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
f_sup, car_10min = rd.read_data(path + '1_new/1_0s_aftermixing_10_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
car_3min_mean = np.mean(car_3min, axis=0)
car_10min_mean = np.mean(car_10min, axis=0)
f_sup, aceta_20sec = rd.read_data(path + '4/4_20_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceta_20sec_mean = np.mean(aceta_20sec, axis=0)
f_sup, aceta_30sec = rd.read_data(path + '4/4_20_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceta_30sec_mean = np.mean(aceta_30sec, axis=0)
f_sup, aceta_1min = rd.read_data(path + '4/4_20_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceta_1min_mean = np.mean(aceta_1min, axis=0)
f_sup, aceta_2min = rd.read_data(path + '4/4_20_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceta_2min_mean = np.mean(aceta_2min, axis=0)
f_sup, aceta_3min = rd.read_data(path + '4/4_20_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
f_sup, aceta_10min = rd.read_data(path + '4/4_20_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceta_3min_mean = np.mean(aceta_3min, axis=0)
aceta_10min_mean = np.mean(aceta_10min, axis=0)
f_sup, aceta_20sec = rd.read_data(path + '4/4_20_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceta_20sec_mean = np.mean(aceta_20sec, axis=0)
f_sup, aceta_30sec = rd.read_data(path + '4/4_30_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceta_30sec_mean = np.mean(aceta_30sec, axis=0)
f_sup, aceta_1min = rd.read_data(path + '4/4_1_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceta_1min_mean = np.mean(aceta_1min, axis=0)
f_sup, aceta_2min = rd.read_data(path + '4/4_2_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceta_2min_mean = np.mean(aceta_2min, axis=0)
f_sup, aceta_3min = rd.read_data(path + '4/4_3_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
f_sup, aceta_10min = rd.read_data(path + '4/4_10_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceta_3min_mean = np.mean(aceta_3min, axis=0)
aceta_10min_mean = np.mean(aceta_10min, axis=0)
f_sup, aceph_20sec = rd.read_data(path + '5/5_20_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceph_20sec_mean = np.mean(aceph_20sec, axis=0)
f_sup, aceph_30sec = rd.read_data(path + '5/5_30_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceph_30sec_mean = np.mean(aceph_30sec, axis=0)
f_sup, aceph_1min = rd.read_data(path + '5/5_1_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceph_1min_mean = np.mean(aceph_1min, axis=0)
f_sup, aceph_2min = rd.read_data(path + '5/5_2_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceph_2min_mean = np.mean(aceph_2min, axis=0)
f_sup, aceph_3min = rd.read_data(path + '5/5_3_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
f_sup, aceph_10min = rd.read_data(path + '5/5_10_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceph_3min_mean = np.mean(aceph_3min, axis=0)
aceph_10min_mean = np.mean(aceph_10min, axis=0)
plt.figure(figsize=(25,15))
plt.plot(f_sup, aceta_20sec_mean / np.max(aceta_20sec_mean), label='20 sec')
plt.plot(f_sup, aceta_30sec_mean / np.max(aceta_30sec_mean), label='30 sec')
plt.plot(f_sup, aceta_1min_mean / np.max(aceta_1min_mean), label='1 min')
plt.plot(f_sup, aceta_2min_mean / np.max(aceta_2min_mean), label='2 min')
plt.plot(f_sup, aceta_3min_mean / np.max(aceta_3min_mean), label='3 min')
plt.plot(f_sup, aceta_10min_mean / np.max(aceta_10min_mean), label='10 min')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Normalized intenisty', fontsize = 16)
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
plt.plot(f_sup, car_20sec_mean, label='20 sec')
plt.plot(f_sup, car_30sec_mean, label='30 sec')
plt.plot(f_sup, car_1min_mean, label='1 min')
plt.plot(f_sup, car_2min_mean, label='2 min')
plt.plot(f_sup, car_3min_mean, label='3 min')
plt.plot(f_sup, car_10min_mean, label='10 min')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Normalized intenisty', fontsize = 16)
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
plt.plot(f_sup, car_20sec_mean, label='20 sec')
#plt.plot(f_sup, car_30sec_mean, label='30 sec')
#plt.plot(f_sup, car_1min_mean, label='1 min')
#plt.plot(f_sup, car_2min_mean, label='2 min')
#plt.plot(f_sup, car_3min_mean, label='3 min')
#plt.plot(f_sup, car_10min_mean, label='10 min')
plt.vlines(f_sup[], ymin=0, ymax=2000, linestyles='dashed')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Normalized intenisty', fontsize = 16)
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
plt.plot(f_sup, car_20sec_mean, label='20 sec')
#plt.plot(f_sup, car_30sec_mean, label='30 sec')
#plt.plot(f_sup, car_1min_mean, label='1 min')
#plt.plot(f_sup, car_2min_mean, label='2 min')
#plt.plot(f_sup, car_3min_mean, label='3 min')
#plt.plot(f_sup, car_10min_mean, label='10 min')
plt.vlines(f_sup[200], ymin=0, ymax=2000, linestyles='dashed')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Normalized intenisty', fontsize = 16)
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.show()
np.where(f_sup >= 300)
plt.figure(figsize=(25,15))
plt.plot(f_sup, car_20sec_mean, label='20 sec')
#plt.plot(f_sup, car_30sec_mean, label='30 sec')
#plt.plot(f_sup, car_1min_mean, label='1 min')
#plt.plot(f_sup, car_2min_mean, label='2 min')
#plt.plot(f_sup, car_3min_mean, label='3 min')
#plt.plot(f_sup, car_10min_mean, label='10 min')
plt.vlines(f_sup[207], ymin=0, ymax=2000, linestyles='dashed')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Normalized intenisty', fontsize = 16)
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.show()
f_sup[207]
plt.figure(figsize=(25,15))
plt.plot(f_sup, car_20sec_mean, label='20 sec')
#plt.plot(f_sup, car_30sec_mean, label='30 sec')
#plt.plot(f_sup, car_1min_mean, label='1 min')
#plt.plot(f_sup, car_2min_mean, label='2 min')
#plt.plot(f_sup, car_3min_mean, label='3 min')
#plt.plot(f_sup, car_10min_mean, label='10 min')
plt.vlines(f_sup[207], ymin=0, ymax=2000, linestyles='dashed')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Normalized intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(car_20sec_mean), 100), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
plt.plot(f_sup, car_20sec_mean, label='20 sec')
#plt.plot(f_sup, car_30sec_mean, label='30 sec')
#plt.plot(f_sup, car_1min_mean, label='1 min')
#plt.plot(f_sup, car_2min_mean, label='2 min')
#plt.plot(f_sup, car_3min_mean, label='3 min')
#plt.plot(f_sup, car_10min_mean, label='10 min')
plt.vlines(f_sup[207], ymin=0, ymax=np.max(car_20sec_mean), linestyles='dashed')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Normalized intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(car_20sec_mean), 100), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
#plt.plot(f_sup, car_20sec_mean, label='20 sec')
#plt.plot(f_sup, car_30sec_mean, label='30 sec')
#plt.plot(f_sup, car_1min_mean, label='1 min')
#plt.plot(f_sup, car_2min_mean, label='2 min')
plt.plot(f_sup, car_3min_mean, label='3 min')
#plt.plot(f_sup, car_10min_mean, label='10 min')
plt.vlines(f_sup[207], ymin=0, ymax=np.max(car_20sec_mean), linestyles='dashed')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Normalized intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(car_20sec_mean), 100), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
#plt.plot(f_sup, car_20sec_mean, label='20 sec')
#plt.plot(f_sup, car_30sec_mean, label='30 sec')
#plt.plot(f_sup, car_1min_mean, label='1 min')
#plt.plot(f_sup, car_2min_mean, label='2 min')
plt.plot(f_sup, car_3min_mean, label='3 min')
#plt.plot(f_sup, car_10min_mean, label='10 min')
plt.vlines(f_sup[207], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Normalized intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(car_3min_mean), 100), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
#plt.plot(f_sup, car_20sec_mean, label='20 sec')
#plt.plot(f_sup, car_30sec_mean, label='30 sec')
#plt.plot(f_sup, car_1min_mean, label='1 min')
#plt.plot(f_sup, car_2min_mean, label='2 min')
plt.plot(f_sup, car_3min_mean, label='3 min')
#plt.plot(f_sup, car_10min_mean, label='10 min')
plt.vlines(f_sup[207], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Normalized intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(car_3min_mean), 200), fontsize=15)
plt.show()
np.where(f_sup >= 900)
plt.figure(figsize=(25,15))
#plt.plot(f_sup, car_20sec_mean, label='20 sec')
#plt.plot(f_sup, car_30sec_mean, label='30 sec')
#plt.plot(f_sup, car_1min_mean, label='1 min')
#plt.plot(f_sup, car_2min_mean, label='2 min')
plt.plot(f_sup, car_3min_mean, label='3 min')
#plt.plot(f_sup, car_10min_mean, label='10 min')
plt.vlines(f_sup[207], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.vlines(f_sup[592], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Normalized intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(car_3min_mean), 200), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
#plt.plot(f_sup, car_20sec_mean, label='20 sec')
#plt.plot(f_sup, car_30sec_mean, label='30 sec')
#plt.plot(f_sup, car_1min_mean, label='1 min')
#plt.plot(f_sup, car_2min_mean, label='2 min')
plt.plot(f_sup, car_3min_mean, label='3 min')
#plt.plot(f_sup, car_10min_mean, label='10 min')
plt.vlines(f_sup[207], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.vlines(f_sup[590], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Normalized intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(car_3min_mean), 200), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
#plt.plot(f_sup, car_20sec_mean, label='20 sec')
#plt.plot(f_sup, car_30sec_mean, label='30 sec')
#plt.plot(f_sup, car_1min_mean, label='1 min')
#plt.plot(f_sup, car_2min_mean, label='2 min')
plt.plot(f_sup, car_3min_mean, label='3 min')
#plt.plot(f_sup, car_10min_mean, label='10 min')
plt.vlines(f_sup[207], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.vlines(f_sup[585], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Normalized intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(car_3min_mean), 200), fontsize=15)
plt.show()
np.where(f_sup >= 1100)
plt.figure(figsize=(25,15))
#plt.plot(f_sup, car_20sec_mean, label='20 sec')
#plt.plot(f_sup, car_30sec_mean, label='30 sec')
#plt.plot(f_sup, car_1min_mean, label='1 min')
#plt.plot(f_sup, car_2min_mean, label='2 min')
plt.plot(f_sup, car_3min_mean, label='3 min')
#plt.plot(f_sup, car_10min_mean, label='10 min')
plt.vlines(f_sup[207], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.vlines(f_sup[585], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.vlines(f_sup[720], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(car_3min_mean), 200), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
#plt.plot(f_sup, car_20sec_mean, label='20 sec')
#plt.plot(f_sup, car_30sec_mean, label='30 sec')
#plt.plot(f_sup, car_1min_mean, label='1 min')
#plt.plot(f_sup, car_2min_mean, label='2 min')
plt.plot(f_sup, car_3min_mean, label='3 min')
#plt.plot(f_sup, car_10min_mean, label='10 min')
plt.vlines(f_sup[207], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.vlines(f_sup[585], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.vlines(f_sup[722], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(car_3min_mean), 200), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
#plt.plot(f_sup, car_20sec_mean, label='20 sec')
#plt.plot(f_sup, car_30sec_mean, label='30 sec')
#plt.plot(f_sup, car_1min_mean, label='1 min')
#plt.plot(f_sup, car_2min_mean, label='2 min')
plt.plot(f_sup, car_3min_mean, label='3 min')
#plt.plot(f_sup, car_10min_mean, label='10 min')
plt.vlines(f_sup[207], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.vlines(f_sup[585], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.vlines(f_sup[725], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(car_3min_mean), 200), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
#plt.plot(f_sup, car_20sec_mean, label='20 sec')
#plt.plot(f_sup, car_30sec_mean, label='30 sec')
#plt.plot(f_sup, car_1min_mean, label='1 min')
#plt.plot(f_sup, car_2min_mean, label='2 min')
plt.plot(f_sup, car_3min_mean, label='3 min')
#plt.plot(f_sup, car_10min_mean, label='10 min')
plt.vlines(f_sup[207], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.vlines(f_sup[585], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.vlines(f_sup[723], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(car_3min_mean), 200), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
#plt.plot(f_sup, car_20sec_mean, label='20 sec')
#plt.plot(f_sup, car_30sec_mean, label='30 sec')
#plt.plot(f_sup, car_1min_mean, label='1 min')
#plt.plot(f_sup, car_2min_mean, label='2 min')
plt.plot(f_sup, car_3min_mean, label='3 min')
#plt.plot(f_sup, car_10min_mean, label='10 min')
plt.vlines(f_sup[207], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.vlines(f_sup[585], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.vlines(f_sup[723], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.vlines(f_sup[740], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(car_3min_mean), 200), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
#plt.plot(f_sup, car_20sec_mean, label='20 sec')
#plt.plot(f_sup, car_30sec_mean, label='30 sec')
#plt.plot(f_sup, car_1min_mean, label='1 min')
#plt.plot(f_sup, car_2min_mean, label='2 min')
plt.plot(f_sup, car_3min_mean, label='3 min')
#plt.plot(f_sup, car_10min_mean, label='10 min')
plt.vlines(f_sup[207], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.vlines(f_sup[585], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.vlines(f_sup[723], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.vlines(f_sup[750], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(car_3min_mean), 200), fontsize=15)
plt.show()
np.where(f_sup >= 1400)
plt.figure(figsize=(25,15))
#plt.plot(f_sup, car_20sec_mean, label='20 sec')
#plt.plot(f_sup, car_30sec_mean, label='30 sec')
#plt.plot(f_sup, car_1min_mean, label='1 min')
#plt.plot(f_sup, car_2min_mean, label='2 min')
plt.plot(f_sup, car_3min_mean, label='3 min')
#plt.plot(f_sup, car_10min_mean, label='10 min')
plt.vlines(f_sup[207], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.vlines(f_sup[585], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.vlines(f_sup[723], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.vlines(f_sup[750], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.vlines(f_sup[913], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(car_3min_mean), 200), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
#plt.plot(f_sup, car_20sec_mean, label='20 sec')
#plt.plot(f_sup, car_30sec_mean, label='30 sec')
#plt.plot(f_sup, car_1min_mean, label='1 min')
#plt.plot(f_sup, car_2min_mean, label='2 min')
plt.plot(f_sup, car_3min_mean, label='3 min')
#plt.plot(f_sup, car_10min_mean, label='10 min')
plt.vlines(f_sup[207], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.vlines(f_sup[585], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.vlines(f_sup[723], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.vlines(f_sup[750], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.vlines(f_sup[912], ymin=0, ymax=np.max(car_3min_mean), linestyles='dashed')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(car_3min_mean), 200), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
plt.plot(f_sup, car_20sec_mean, label='20 sec')
#plt.plot(f_sup, car_30sec_mean, label='30 sec')
#plt.plot(f_sup, car_1min_mean, label='1 min')
#plt.plot(f_sup, car_2min_mean, label='2 min')
#plt.plot(f_sup, car_3min_mean, label='3 min')
#plt.plot(f_sup, car_10min_mean, label='10 min')
plt.vlines(f_sup[207], ymin=0, ymax=np.max(car_20sec_mean), linestyles='dashed')
plt.vlines(f_sup[585], ymin=0, ymax=np.max(car_20sec_mean), linestyles='dashed')
plt.vlines(f_sup[723], ymin=0, ymax=np.max(car_20sec_mean), linestyles='dashed')
plt.vlines(f_sup[750], ymin=0, ymax=np.max(car_20sec_mean), linestyles='dashed')
plt.vlines(f_sup[912], ymin=0, ymax=np.max(car_20sec_mean), linestyles='dashed')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(car_20sec_mean), 100), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
#plt.plot(f_sup, car_20sec_mean, label='20 sec')
plt.plot(f_sup, car_30sec_mean, label='30 sec')
#plt.plot(f_sup, car_1min_mean, label='1 min')
#plt.plot(f_sup, car_2min_mean, label='2 min')
#plt.plot(f_sup, car_3min_mean, label='3 min')
#plt.plot(f_sup, car_10min_mean, label='10 min')
plt.vlines(f_sup[207], ymin=0, ymax=np.max(car_30sec_mean), linestyles='dashed')
plt.vlines(f_sup[585], ymin=0, ymax=np.max(car_30sec_mean), linestyles='dashed')
plt.vlines(f_sup[723], ymin=0, ymax=np.max(car_30sec_mean), linestyles='dashed')
plt.vlines(f_sup[750], ymin=0, ymax=np.max(car_30sec_mean), linestyles='dashed')
plt.vlines(f_sup[912], ymin=0, ymax=np.max(car_30sec_mean), linestyles='dashed')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(car_30sec_mean), 100), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
#plt.plot(f_sup, car_20sec_mean, label='20 sec')
#plt.plot(f_sup, car_30sec_mean, label='30 sec')
plt.plot(f_sup, car_1min_mean, label='1 min')
#plt.plot(f_sup, car_2min_mean, label='2 min')
#plt.plot(f_sup, car_3min_mean, label='3 min')
#plt.plot(f_sup, car_10min_mean, label='10 min')
plt.vlines(f_sup[207], ymin=0, ymax=np.max(car_1min_mean), linestyles='dashed')
plt.vlines(f_sup[585], ymin=0, ymax=np.max(car_1min_mean), linestyles='dashed')
plt.vlines(f_sup[723], ymin=0, ymax=np.max(car_1min_mean), linestyles='dashed')
plt.vlines(f_sup[750], ymin=0, ymax=np.max(car_1min_mean), linestyles='dashed')
plt.vlines(f_sup[912], ymin=0, ymax=np.max(car_1min_mean), linestyles='dashed')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(car_1min_mean), 100), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
#plt.plot(f_sup, car_20sec_mean, label='20 sec')
#plt.plot(f_sup, car_30sec_mean, label='30 sec')
#plt.plot(f_sup, car_1min_mean, label='1 min')
plt.plot(f_sup, car_2min_mean, label='2 min')
#plt.plot(f_sup, car_3min_mean, label='3 min')
#plt.plot(f_sup, car_10min_mean, label='10 min')
plt.vlines(f_sup[207], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.vlines(f_sup[585], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.vlines(f_sup[723], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.vlines(f_sup[750], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.vlines(f_sup[912], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(car_2min_mean), 100), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
#plt.plot(f_sup, car_20sec_mean, label='20 sec')
#plt.plot(f_sup, car_30sec_mean, label='30 sec')
#plt.plot(f_sup, car_1min_mean, label='1 min')
plt.plot(f_sup, car_2min_mean, label='2 min')
#plt.plot(f_sup, car_3min_mean, label='3 min')
#plt.plot(f_sup, car_10min_mean, label='10 min')
plt.vlines(f_sup[207], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.vlines(f_sup[585], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.vlines(f_sup[723], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.vlines(f_sup[750], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.vlines(f_sup[912], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(car_2min_mean), 200), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
#plt.plot(f_sup, car_20sec_mean, label='20 sec')
#plt.plot(f_sup, car_30sec_mean, label='30 sec')
#plt.plot(f_sup, car_1min_mean, label='1 min')
plt.plot(f_sup, car_2min_mean, label='2 min')
#plt.plot(f_sup, car_3min_mean, label='3 min')
#plt.plot(f_sup, car_10min_mean, label='10 min')
plt.vlines(f_sup[207], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.vlines(f_sup[585], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.vlines(f_sup[723], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.vlines(f_sup[750], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.vlines(f_sup[912], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(car_2min_mean), 300), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
#plt.plot(f_sup, car_20sec_mean, label='20 sec')
#plt.plot(f_sup, car_30sec_mean, label='30 sec')
#plt.plot(f_sup, car_1min_mean, label='1 min')
plt.plot(f_sup, car_2min_mean, label='2 min')
#plt.plot(f_sup, car_3min_mean, label='3 min')
#plt.plot(f_sup, car_10min_mean, label='10 min')
plt.vlines(f_sup[207], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.vlines(f_sup[585], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.vlines(f_sup[723], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.vlines(f_sup[750], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.vlines(f_sup[912], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(car_2min_mean), 400), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
#plt.plot(f_sup, car_20sec_mean, label='20 sec')
#plt.plot(f_sup, car_30sec_mean, label='30 sec')
#plt.plot(f_sup, car_1min_mean, label='1 min')
plt.plot(f_sup, car_2min_mean, label='2 min')
#plt.plot(f_sup, car_3min_mean, label='3 min')
#plt.plot(f_sup, car_10min_mean, label='10 min')
plt.vlines(f_sup[207], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.vlines(f_sup[585], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.vlines(f_sup[723], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.vlines(f_sup[750], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.vlines(f_sup[912], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(car_2min_mean), 500), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
#plt.plot(f_sup, car_20sec_mean, label='20 sec')
#plt.plot(f_sup, car_30sec_mean, label='30 sec')
#plt.plot(f_sup, car_1min_mean, label='1 min')
plt.plot(f_sup, car_2min_mean, label='2 min')
#plt.plot(f_sup, car_3min_mean, label='3 min')
#plt.plot(f_sup, car_10min_mean, label='10 min')
plt.vlines(f_sup[207], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.vlines(f_sup[585], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.vlines(f_sup[723], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.vlines(f_sup[750], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.vlines(f_sup[912], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(car_2min_mean), 600), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
#plt.plot(f_sup, car_20sec_mean, label='20 sec')
#plt.plot(f_sup, car_30sec_mean, label='30 sec')
#plt.plot(f_sup, car_1min_mean, label='1 min')
plt.plot(f_sup, car_2min_mean, label='2 min')
#plt.plot(f_sup, car_3min_mean, label='3 min')
#plt.plot(f_sup, car_10min_mean, label='10 min')
plt.vlines(f_sup[207], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.vlines(f_sup[585], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.vlines(f_sup[723], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.vlines(f_sup[750], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.vlines(f_sup[912], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(car_2min_mean), 800), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
#plt.plot(f_sup, car_20sec_mean, label='20 sec')
#plt.plot(f_sup, car_30sec_mean, label='30 sec')
#plt.plot(f_sup, car_1min_mean, label='1 min')
plt.plot(f_sup, car_2min_mean, label='2 min')
plt.plot(f_sup, car_3min_mean, label='3 min')
#plt.plot(f_sup, car_10min_mean, label='10 min')
plt.vlines(f_sup[207], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.vlines(f_sup[585], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.vlines(f_sup[723], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.vlines(f_sup[750], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.vlines(f_sup[912], ymin=0, ymax=np.max(car_2min_mean), linestyles='dashed')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(car_2min_mean), 800), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
#plt.plot(f_sup, car_20sec_mean, label='20 sec')
#plt.plot(f_sup, car_30sec_mean, label='30 sec')
#plt.plot(f_sup, car_1min_mean, label='1 min')
#plt.plot(f_sup, car_2min_mean, label='2 min')
#plt.plot(f_sup, car_3min_mean, label='3 min')
plt.plot(f_sup, car_10min_mean, label='10 min')
plt.vlines(f_sup[207], ymin=0, ymax=np.max(car_10min_mean), linestyles='dashed')
plt.vlines(f_sup[585], ymin=0, ymax=np.max(car_10min_mean), linestyles='dashed')
plt.vlines(f_sup[723], ymin=0, ymax=np.max(car_10min_mean), linestyles='dashed')
plt.vlines(f_sup[750], ymin=0, ymax=np.max(car_10min_mean), linestyles='dashed')
plt.vlines(f_sup[912], ymin=0, ymax=np.max(car_10min_mean), linestyles='dashed')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(car_10min_mean), 800), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
#plt.plot(f_sup, car_20sec_mean, label='20 sec')
#plt.plot(f_sup, car_30sec_mean, label='30 sec')
#plt.plot(f_sup, car_1min_mean, label='1 min')
#plt.plot(f_sup, car_2min_mean, label='2 min')
#plt.plot(f_sup, car_3min_mean, label='3 min')
plt.plot(f_sup, car_10min_mean, label='10 min')
plt.vlines(f_sup[207], ymin=0, ymax=np.max(car_10min_mean), linestyles='dashed')
plt.vlines(f_sup[585], ymin=0, ymax=np.max(car_10min_mean), linestyles='dashed')
plt.vlines(f_sup[723], ymin=0, ymax=np.max(car_10min_mean), linestyles='dashed')
plt.vlines(f_sup[750], ymin=0, ymax=np.max(car_10min_mean), linestyles='dashed')
plt.vlines(f_sup[912], ymin=0, ymax=np.max(car_10min_mean), linestyles='dashed')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(car_10min_mean), 200), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
#plt.plot(f_sup, car_20sec_mean, label='20 sec')
#plt.plot(f_sup, car_30sec_mean, label='30 sec')
#plt.plot(f_sup, car_1min_mean, label='1 min')
#plt.plot(f_sup, car_2min_mean, label='2 min')
#plt.plot(f_sup, car_3min_mean, label='3 min')
plt.plot(f_sup, car_10min_mean, label='10 min')
plt.vlines(f_sup[207], ymin=0, ymax=np.max(car_10min_mean), linestyles='dashed')
plt.vlines(f_sup[585], ymin=0, ymax=np.max(car_10min_mean), linestyles='dashed')
plt.vlines(f_sup[723], ymin=0, ymax=np.max(car_10min_mean), linestyles='dashed')
plt.vlines(f_sup[750], ymin=0, ymax=np.max(car_10min_mean), linestyles='dashed')
plt.vlines(f_sup[912], ymin=0, ymax=np.max(car_10min_mean), linestyles='dashed')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(car_10min_mean), 100), fontsize=15)
plt.show()
f_sup[207]
f_sup[585]
f_sup[723]
f_sup[750]
f_sup[912]
plt.figure(figsize=(25,15))
plt.plot(f_sup, aceta_20sec_mean, label='20 sec')
plt.vlines(f_sup[207], ymin=0, ymax=np.max(aceta_20sec_mean), linestyles='dashed')
plt.vlines(f_sup[585], ymin=0, ymax=np.max(aceta_20sec_mean), linestyles='dashed')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(aceta_20sec_mean), 100), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
plt.plot(f_sup, aceta_20sec_mean, label='20 sec')
plt.vlines(f_sup[585], ymin=0, ymax=np.max(aceta_20sec_mean), linestyles='dashed')
plt.vlines(f_sup[0], ymin=0, ymax=np.max(aceta_20sec_mean), linestyles='dashed')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(aceta_20sec_mean), 100), fontsize=15)
plt.show()
np.where(f_sup >= 2120)
plt.figure(figsize=(25,15))
plt.plot(f_sup, aceta_20sec_mean, label='20 sec')
plt.vlines(f_sup[585], ymin=0, ymax=np.max(aceta_20sec_mean), linestyles='dashed')
plt.vlines(f_sup[1375], ymin=0, ymax=np.max(aceta_20sec_mean), linestyles='dashed')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(aceta_20sec_mean), 100), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
plt.plot(f_sup, aceta_3min_mean, label='20 sec')
plt.vlines(f_sup[585], ymin=0, ymax=np.max(aceta_3min_mean), linestyles='dashed')
plt.vlines(f_sup[1375], ymin=0, ymax=np.max(aceta_3min_mean), linestyles='dashed')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(aceta_3min_mean), 100), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
plt.plot(f_sup, aceta_3min_mean, label='20 sec')
plt.vlines(f_sup[595], ymin=0, ymax=np.max(aceta_3min_mean), linestyles='dashed')
plt.vlines(f_sup[1365], ymin=0, ymax=np.max(aceta_3min_mean), linestyles='dashed')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(aceta_3min_mean), 100), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
plt.plot(f_sup, aceta_3min_mean, label='20 sec')
plt.vlines(f_sup[595], ymin=0, ymax=np.max(aceta_3min_mean), linestyles='dashed')
plt.vlines(f_sup[1366], ymin=0, ymax=np.max(aceta_3min_mean), linestyles='dashed')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(aceta_3min_mean), 100), fontsize=15)
plt.show()
f_sup[595]
f_sup[1365]
plt.figure(figsize=(25,15))
plt.plot(f_sup, aceta_20sec_mean, label='20 sec')
plt.vlines(f_sup[595], ymin=0, ymax=np.max(aceta_20sec_mean), linestyles='dashed')
plt.vlines(f_sup[1366], ymin=0, ymax=np.max(aceta_20sec_mean), linestyles='dashed')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(aceta_20sec_mean), 100), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
plt.plot(f_sup, aceta_30sec_mean, label='20 sec')
plt.vlines(f_sup[595], ymin=0, ymax=np.max(aceta_30sec_mean), linestyles='dashed')
plt.vlines(f_sup[1366], ymin=0, ymax=np.max(aceta_30sec_mean), linestyles='dashed')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(aceta_30sec_mean), 100), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
plt.plot(f_sup, aceta_30sec_mean, label='20 sec')
plt.vlines(f_sup[595], ymin=0, ymax=np.max(aceta_30sec_mean), linestyles='dashed')
plt.vlines(f_sup[1366], ymin=0, ymax=np.max(aceta_30sec_mean), linestyles='dashed')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(aceta_30sec_mean), 300), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
plt.plot(f_sup, aceta_1min_mean, label='20 sec')
plt.vlines(f_sup[595], ymin=0, ymax=np.max(aceta_1min_mean), linestyles='dashed')
plt.vlines(f_sup[1366], ymin=0, ymax=np.max(aceta_1min_mean), linestyles='dashed')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(aceta_1min_mean), 300), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
plt.plot(f_sup, aceta_1min_mean, label='20 sec')
plt.vlines(f_sup[595], ymin=0, ymax=np.max(aceta_1min_mean), linestyles='dashed')
plt.vlines(f_sup[1366], ymin=0, ymax=np.max(aceta_1min_mean), linestyles='dashed')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(aceta_1min_mean), 200), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
plt.plot(f_sup, aceta_2min_mean, label='20 sec')
plt.vlines(f_sup[595], ymin=0, ymax=np.max(aceta_2min_mean), linestyles='dashed')
plt.vlines(f_sup[1366], ymin=0, ymax=np.max(aceta_2min_mean), linestyles='dashed')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(aceta_2min_mean), 200), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
plt.plot(f_sup, aceta_3min_mean, label='20 sec')
plt.vlines(f_sup[595], ymin=0, ymax=np.max(aceta_3min_mean), linestyles='dashed')
plt.vlines(f_sup[1366], ymin=0, ymax=np.max(aceta_3min_mean), linestyles='dashed')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(aceta_3min_mean), 200), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
plt.plot(f_sup, aceta_10min_mean, label='20 sec')
plt.vlines(f_sup[595], ymin=0, ymax=np.max(aceta_10min_mean), linestyles='dashed')
plt.vlines(f_sup[1366], ymin=0, ymax=np.max(aceta_10min_mean), linestyles='dashed')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(aceta_10min_mean), 200), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
plt.plot(f_sup, aceta_10min_mean, label='20 sec')
plt.vlines(f_sup[595], ymin=0, ymax=np.max(aceta_10min_mean), linestyles='dashed')
plt.vlines(f_sup[1366], ymin=0, ymax=np.max(aceta_10min_mean), linestyles='dashed')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(aceta_10min_mean), 50), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
plt.plot(f_sup, aceph_20sec_mean, label='20 sec')
plt.vlines(f_sup[595], ymin=0, ymax=np.max(aceph_20sec_mean), linestyles='dashed')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(aceph_20sec_mean), 50), fontsize=15)
plt.show()
np.where(f_sup>=581)
plt.figure(figsize=(25,15))
plt.plot(f_sup, aceph_20sec_mean, label='20 sec')
plt.vlines(f_sup[387], ymin=0, ymax=np.max(aceph_20sec_mean), linestyles='dashed')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(aceph_20sec_mean), 50), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
plt.plot(f_sup, aceph_20sec_mean, label='20 sec')
plt.vlines(f_sup[386], ymin=0, ymax=np.max(aceph_20sec_mean), linestyles='dashed')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(aceph_20sec_mean), 50), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
plt.plot(f_sup, aceph_30sec_mean, label='20 sec')
plt.vlines(f_sup[386], ymin=0, ymax=np.max(aceph_30sec_mean), linestyles='dashed')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(aceph_30sec_mean), 50), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
plt.plot(f_sup, aceph_30sec_mean, label='20 sec')
plt.vlines(f_sup[386], ymin=0, ymax=np.max(aceph_30sec_mean), linestyles='dashed')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(aceph_30sec_mean), 200), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
plt.plot(f_sup, aceph_1min_mean, label='20 sec')
plt.vlines(f_sup[386], ymin=0, ymax=np.max(aceph_1min_mean), linestyles='dashed')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(aceph_1min_mean), 200), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
plt.plot(f_sup, aceph_1min_mean, label='20 sec')
plt.vlines(f_sup[386], ymin=0, ymax=np.max(aceph_1min_mean), linestyles='dashed')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(aceph_1min_mean), 50), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
plt.plot(f_sup, aceph_2min_mean, label='20 sec')
plt.vlines(f_sup[386], ymin=0, ymax=np.max(aceph_2min_mean), linestyles='dashed')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(aceph_2min_mean), 50), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
plt.plot(f_sup, aceph_3min_mean, label='20 sec')
plt.vlines(f_sup[386], ymin=0, ymax=np.max(aceph_3min_mean), linestyles='dashed')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(aceph_3min_mean), 50), fontsize=15)
plt.show()
plt.figure(figsize=(25,15))
plt.plot(f_sup, aceph_10min_mean, label='20 sec')
plt.vlines(f_sup[386], ymin=0, ymax=np.max(aceph_10min_mean), linestyles='dashed')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0 , f_sup[-1], 200), fontsize=15)
plt.yticks(np.arange(0, np.max(aceph_10min_mean), 50), fontsize=15)
plt.show()
f_sup[386]
plt.figure(figsize=(25,15))
plt.plot(x_data_0426, uv_data_04_26_batch2, '^', label='2021-04-27 batch 2')
plt.plot(x_data_0706, uv_data_04_26_batch3, '^', label='2021-04-27 batch 3')
plt.plot(x_data_0706, uv_data_07_06, 'o', label='2021-07-07')
plt.plot(x_data_0810, uv_data_08_10_5X, 's', label='2021-08-10 5X diluted')
plt.plot(x_data_1029, uv_data_20sec, 'P', label='2021-10-29 20sec')
plt.plot(x_data_1029, uv_data_30sec, 'P', label='2021-10-29 30sec')
plt.plot(x_data_1029, uv_data_1min, 'P', label='2021-10-29 1min')
plt.plot(x_data_1029, uv_data_2min, 'P', label='2021-10-29 2min')
plt.plot(x_data_1029, uv_data_3min, 'P', label='2021-10-29 3min')
plt.plot(x_data_1029, uv_data_10min, 'P', label='2021-10-29 10min')
plt.legend()
plt.title('Absorbance of the different colloidal sol.', fontsize=16)
plt.xlabel('Wavelength', fontsize = 16)
plt.ylabel('Abs %', fontsize = 16)
plt.xticks(fontsize=15)
plt.yticks(fontsize=11)
plt.show()
plt.figure(figsize=(25,15))
plt.plot(x_data_0426, uv_data_04_26_batch2, '^', label='2021-04-27 batch 2')
plt.plot(x_data_0706, uv_data_04_26_batch3, '^', label='2021-04-27 batch 3')
plt.plot(x_data_0706, uv_data_07_06, 'o', label='2021-07-07')
plt.plot(x_data_0810, uv_data_08_10_5X, 's', label='2021-08-10 5X diluted')
plt.plot(x_data_1029, uv_data_20sec, 'P', label='2021-10-29 20sec')
plt.plot(x_data_1029, uv_data_30sec, 'P', label='2021-10-29 30sec')
plt.plot(x_data_1029, uv_data_1min, 'P', label='2021-10-29 1min')
plt.plot(x_data_1029, uv_data_2min, 'P', label='2021-10-29 2min')
plt.plot(x_data_1029, uv_data_3min, 'P', label='2021-10-29 3min')
plt.plot(x_data_1029, uv_data_10min, 'P', label='2021-10-29 10min')
plt.vlines(x_data, ymin=np.min(uv_data_07_06), np.max(uv_data_07_06), linestyles='dashed')
plt.legend()
plt.title('Absorbance of the different colloidal sol.', fontsize=16)
plt.xlabel('Wavelength', fontsize = 16)
plt.ylabel('Abs %', fontsize = 16)
plt.xticks(fontsize=15)
plt.yticks(fontsize=11)
plt.show()
plt.figure(figsize=(25,15))
plt.plot(x_data_0426, uv_data_04_26_batch2, '^', label='2021-04-27 batch 2')
plt.plot(x_data_0706, uv_data_04_26_batch3, '^', label='2021-04-27 batch 3')
plt.plot(x_data_0706, uv_data_07_06, 'o', label='2021-07-07')
plt.plot(x_data_0810, uv_data_08_10_5X, 's', label='2021-08-10 5X diluted')
plt.plot(x_data_1029, uv_data_20sec, 'P', label='2021-10-29 20sec')
plt.plot(x_data_1029, uv_data_30sec, 'P', label='2021-10-29 30sec')
plt.plot(x_data_1029, uv_data_1min, 'P', label='2021-10-29 1min')
plt.plot(x_data_1029, uv_data_2min, 'P', label='2021-10-29 2min')
plt.plot(x_data_1029, uv_data_3min, 'P', label='2021-10-29 3min')
plt.plot(x_data_1029, uv_data_10min, 'P', label='2021-10-29 10min')
plt.vlines(x_data[100], ymin=np.min(uv_data_07_06), np.max(uv_data_07_06), linestyles='dashed')
plt.legend()
plt.title('Absorbance of the different colloidal sol.', fontsize=16)
plt.xlabel('Wavelength', fontsize = 16)
plt.ylabel('Abs %', fontsize = 16)
plt.xticks(fontsize=15)
plt.yticks(fontsize=11)
plt.show()
plt.figure(figsize=(25,15))
plt.plot(x_data_0426, uv_data_04_26_batch2, '^', label='2021-04-27 batch 2')
plt.plot(x_data_0706, uv_data_04_26_batch3, '^', label='2021-04-27 batch 3')
plt.plot(x_data_0706, uv_data_07_06, 'o', label='2021-07-07')
plt.plot(x_data_0810, uv_data_08_10_5X, 's', label='2021-08-10 5X diluted')
plt.plot(x_data_1029, uv_data_20sec, 'P', label='2021-10-29 20sec')
plt.plot(x_data_1029, uv_data_30sec, 'P', label='2021-10-29 30sec')
plt.plot(x_data_1029, uv_data_1min, 'P', label='2021-10-29 1min')
plt.plot(x_data_1029, uv_data_2min, 'P', label='2021-10-29 2min')
plt.plot(x_data_1029, uv_data_3min, 'P', label='2021-10-29 3min')
plt.plot(x_data_1029, uv_data_10min, 'P', label='2021-10-29 10min')
plt.vlines(x_data[100], ymin=np.min(uv_data_07_06), ymax=np.max(uv_data_07_06), linestyles='dashed')
plt.legend()
plt.title('Absorbance of the different colloidal sol.', fontsize=16)
plt.xlabel('Wavelength', fontsize = 16)
plt.ylabel('Abs %', fontsize = 16)
plt.xticks(fontsize=15)
plt.yticks(fontsize=11)
plt.show()
plt.figure(figsize=(25,15))
plt.plot(x_data_0426, uv_data_04_26_batch2, '^', label='2021-04-27 batch 2')
plt.plot(x_data_0706, uv_data_04_26_batch3, '^', label='2021-04-27 batch 3')
plt.plot(x_data_0706, uv_data_07_06, 'o', label='2021-07-07')
plt.plot(x_data_0810, uv_data_08_10_5X, 's', label='2021-08-10 5X diluted')
plt.plot(x_data_1029, uv_data_20sec, 'P', label='2021-10-29 20sec')
plt.plot(x_data_1029, uv_data_30sec, 'P', label='2021-10-29 30sec')
plt.plot(x_data_1029, uv_data_1min, 'P', label='2021-10-29 1min')
plt.plot(x_data_1029, uv_data_2min, 'P', label='2021-10-29 2min')
plt.plot(x_data_1029, uv_data_3min, 'P', label='2021-10-29 3min')
plt.plot(x_data_1029, uv_data_10min, 'P', label='2021-10-29 10min')
plt.vlines(x_data[50], ymin=np.min(uv_data_07_06), ymax=np.max(uv_data_07_06), linestyles='dashed')
plt.legend()
plt.title('Absorbance of the different colloidal sol.', fontsize=16)
plt.xlabel('Wavelength', fontsize = 16)
plt.ylabel('Abs %', fontsize = 16)
plt.xticks(fontsize=15)
plt.yticks(fontsize=11)
plt.show()
plt.figure(figsize=(25,15))
plt.plot(x_data_0426, uv_data_04_26_batch2, '^', label='2021-04-27 batch 2')
plt.plot(x_data_0706, uv_data_04_26_batch3, '^', label='2021-04-27 batch 3')
plt.plot(x_data_0706, uv_data_07_06, 'o', label='2021-07-07')
plt.plot(x_data_0810, uv_data_08_10_5X, 's', label='2021-08-10 5X diluted')
plt.plot(x_data_1029, uv_data_20sec, 'P', label='2021-10-29 20sec')
plt.plot(x_data_1029, uv_data_30sec, 'P', label='2021-10-29 30sec')
plt.plot(x_data_1029, uv_data_1min, 'P', label='2021-10-29 1min')
plt.plot(x_data_1029, uv_data_2min, 'P', label='2021-10-29 2min')
plt.plot(x_data_1029, uv_data_3min, 'P', label='2021-10-29 3min')
plt.plot(x_data_1029, uv_data_10min, 'P', label='2021-10-29 10min')
plt.vlines(x_data[55], ymin=np.min(uv_data_07_06), ymax=np.max(uv_data_07_06), linestyles='dashed')
plt.legend()
plt.title('Absorbance of the different colloidal sol.', fontsize=16)
plt.xlabel('Wavelength', fontsize = 16)
plt.ylabel('Abs %', fontsize = 16)
plt.xticks(fontsize=15)
plt.yticks(fontsize=11)
plt.show()
plt.figure(figsize=(25,15))
plt.plot(x_data_0426, uv_data_04_26_batch2, '^', label='2021-04-27 batch 2')
plt.plot(x_data_0706, uv_data_04_26_batch3, '^', label='2021-04-27 batch 3')
plt.plot(x_data_0706, uv_data_07_06, 'o', label='2021-07-07')
plt.plot(x_data_0810, uv_data_08_10_5X, 's', label='2021-08-10 5X diluted')
plt.plot(x_data_1029, uv_data_20sec, 'P', label='2021-10-29 20sec')
plt.plot(x_data_1029, uv_data_30sec, 'P', label='2021-10-29 30sec')
plt.plot(x_data_1029, uv_data_1min, 'P', label='2021-10-29 1min')
plt.plot(x_data_1029, uv_data_2min, 'P', label='2021-10-29 2min')
plt.plot(x_data_1029, uv_data_3min, 'P', label='2021-10-29 3min')
plt.plot(x_data_1029, uv_data_10min, 'P', label='2021-10-29 10min')
plt.vlines(x_data[55], ymin=np.min(uv_data_07_06), ymax=np.max(uv_data_07_06), linestyles='dashed')
plt.vlines(x_data[53], ymin=np.min(uv_data_07_06), ymax=np.max(uv_data_07_06), linestyles='dashed')
plt.legend()
plt.title('Absorbance of the different colloidal sol.', fontsize=16)
plt.xlabel('Wavelength', fontsize = 16)
plt.ylabel('Abs %', fontsize = 16)
plt.xticks(fontsize=15)
plt.yticks(fontsize=11)
plt.show()
plt.figure(figsize=(25,15))
plt.plot(x_data_0426, uv_data_04_26_batch2, '^', label='2021-04-27 batch 2')
plt.plot(x_data_0706, uv_data_04_26_batch3, '^', label='2021-04-27 batch 3')
plt.plot(x_data_0706, uv_data_07_06, 'o', label='2021-07-07')
plt.plot(x_data_0810, uv_data_08_10_5X, 's', label='2021-08-10 5X diluted')
plt.plot(x_data_1029, uv_data_20sec, 'P', label='2021-10-29 20sec')
plt.plot(x_data_1029, uv_data_30sec, 'P', label='2021-10-29 30sec')
plt.plot(x_data_1029, uv_data_1min, 'P', label='2021-10-29 1min')
plt.plot(x_data_1029, uv_data_2min, 'P', label='2021-10-29 2min')
plt.plot(x_data_1029, uv_data_3min, 'P', label='2021-10-29 3min')
plt.plot(x_data_1029, uv_data_10min, 'P', label='2021-10-29 10min')
plt.vlines(x_data[55], ymin=np.min(uv_data_07_06), ymax=np.max(uv_data_07_06), linestyles='dashed')
plt.vlines(x_data[52], ymin=np.min(uv_data_07_06), ymax=np.max(uv_data_07_06), linestyles='dashed')
plt.legend()
plt.title('Absorbance of the different colloidal sol.', fontsize=16)
plt.xlabel('Wavelength', fontsize = 16)
plt.ylabel('Abs %', fontsize = 16)
plt.xticks(fontsize=15)
plt.yticks(fontsize=11)
plt.show()
print(x_data_0426)
%history -f 2021_11_09_logss.py
