%loadext autoreload
%load_ext autoreload
%autoreload 2
from tools.ramanflow.read_data import ReadData as rd
pwd
cd Coding/Raman/
from tools.ramanflow.read_data import ReadData as rd
f_sup, car_20sec = rd.read_data(path + '1_new/1_0s_aftermixing_20_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
car_20sec_mean = np.mean(car_20sec, axis=0)
plt.plot(f_sup, car_20sec_mean)
f_sup, car_30sec = rd.read_data(path + '1_new/1_0s_aftermixing_30_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
car_30sec_mean = np.mean(car_30sec, axis=0)
f_sup, car_1min = rd.read_data(path + '1_new/1_0s_aftermixing_1_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
car_1min_mean = np.mean(car_1min, axis=0)
f_sup, car_2min = rd.read_data(path + '1_new/1_0s_aftermixing_2_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
car_2min_mean = np.mean(car_2min, axis=0)
f_sup, car_3min = rd.read_data(path + '1_new/1_0s_aftermixing_3_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
f_sup, car_10min = rd.read_data(path + '1_new/1_0s_aftermixing_10_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
car_3min_mean = np.mean(car_3min, axis=0)
car_10min_mean = np.mean(car_10min, axis=0)
path = 'data/20211029 multiple colloidal SERS test/'
f_sup, car_20sec = rd.read_data(path + '1_new/1_0s_aftermixing_20_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
car_20sec_mean = np.mean(car_20sec, axis=0)
plt.plot(f_sup, car_20sec_mean)
f_sup, car_30sec = rd.read_data(path + '1_new/1_0s_aftermixing_30_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
car_30sec_mean = np.mean(car_30sec, axis=0)
f_sup, car_1min = rd.read_data(path + '1_new/1_0s_aftermixing_1_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
car_1min_mean = np.mean(car_1min, axis=0)
f_sup, car_2min = rd.read_data(path + '1_new/1_0s_aftermixing_2_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
car_2min_mean = np.mean(car_2min, axis=0)
f_sup, car_3min = rd.read_data(path + '1_new/1_0s_aftermixing_3_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
f_sup, car_10min = rd.read_data(path + '1_new/1_0s_aftermixing_10_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
car_3min_mean = np.mean(car_3min, axis=0)
car_10min_mean = np.mean(car_10min, axis=0)
import numpy as np
import matplotlib.pyplot as plt
f_sup, car_20sec = rd.read_data(path + '1_new/1_0s_aftermixing_20_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
car_20sec_mean = np.mean(car_20sec, axis=0)
plt.plot(f_sup, car_20sec_mean)
f_sup, car_30sec = rd.read_data(path + '1_new/1_0s_aftermixing_30_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
car_30sec_mean = np.mean(car_30sec, axis=0)
f_sup, car_1min = rd.read_data(path + '1_new/1_0s_aftermixing_1_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
car_1min_mean = np.mean(car_1min, axis=0)
f_sup, car_2min = rd.read_data(path + '1_new/1_0s_aftermixing_2_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
car_2min_mean = np.mean(car_2min, axis=0)
f_sup, car_3min = rd.read_data(path + '1_new/1_0s_aftermixing_3_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
f_sup, car_10min = rd.read_data(path + '1_new/1_0s_aftermixing_10_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
car_3min_mean = np.mean(car_3min, axis=0)
car_10min_mean = np.mean(car_10min, axis=0)
f_sup, aceta_20sec = rd.read_data(path + '4/4_20_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceta_20sec_mean = np.mean(aceta_20sec, axis=0)
f_sup, aceta_30sec = rd.read_data(path + '4/4_20_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceta_30sec_mean = np.mean(aceta_30sec, axis=0)
f_sup, aceta_1min = rd.read_data(path + '4/4_20_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceta_1min_mean = np.mean(aceta_1min, axis=0)
f_sup, aceta_2min = rd.read_data(path + '4/4_20_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceta_2min_mean = np.mean(aceta_2min, axis=0)
f_sup, aceta_3min = rd.read_data(path + '4/4_20_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
f_sup, aceta_10min = rd.read_data(path + '4/4_20_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceta_3min_mean = np.mean(aceta_3min, axis=0)
aceta_10min_mean = np.mean(aceta_10min, axis=0)
f_sup, aceta_20sec = rd.read_data(path + '4/4_20_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceta_20sec_mean = np.mean(aceta_20sec, axis=0)
f_sup, aceta_30sec = rd.read_data(path + '4/4_30_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceta_30sec_mean = np.mean(aceta_30sec, axis=0)
f_sup, aceta_1min = rd.read_data(path + '4/4_1_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceta_1min_mean = np.mean(aceta_1min, axis=0)
f_sup, aceta_2min = rd.read_data(path + '4/4_2_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceta_2min_mean = np.mean(aceta_2min, axis=0)
f_sup, aceta_3min = rd.read_data(path + '4/4_3_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
f_sup, aceta_10min = rd.read_data(path + '4/4_10_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceta_3min_mean = np.mean(aceta_3min, axis=0)
aceta_10min_mean = np.mean(aceta_10min, axis=0)
f_sup, aceph_20sec = rd.read_data(path + '5/5_20_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceph_20sec_mean = np.mean(aceph_20sec, axis=0)
f_sup, aceph_30sec = rd.read_data(path + '5/5_30_sec_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceph_30sec_mean = np.mean(aceph_30sec, axis=0)
f_sup, aceph_1min = rd.read_data(path + '5/5_1_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceph_1min_mean = np.mean(aceph_1min, axis=0)
f_sup, aceph_2min = rd.read_data(path + '5/5_2_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceph_2min_mean = np.mean(aceph_2min, axis=0)
f_sup, aceph_3min = rd.read_data(path + '5/5_3_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
f_sup, aceph_10min = rd.read_data(path + '5/5_10_min_coll_6X6_spectral_mapping_1s_msrmnt_4.tif')
aceph_3min_mean = np.mean(aceph_3min, axis=0)
aceph_10min_mean = np.mean(aceph_10min, axis=0)
plt.figure(figsize=(15,10))
plt.plot(f_sup, car_30sec_mean / np.max(car_30sec_mean), label='30 sec')
plt.plot(f_sup, car_1min_mean / np.max(car_1min_mean), label='1 min')
plt.plot(f_sup, car_3min_mean) / np.max(car_3min_mean), label='3 min')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Normalized intenisty', fontsize = 16)
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.show()
plt.figure(figsize=(15,10))
plt.plot(f_sup, car_30sec_mean / np.max(car_30sec_mean), label='30 sec')
plt.plot(f_sup, car_1min_mean / np.max(car_1min_mean), label='1 min')
plt.plot(f_sup, car_3min_mean / np.max(car_3min_mean), label='3 min')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Normalized intenisty', fontsize = 16)
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.show()
plt.figure(figsize=(20,15))
plt.plot(f_sup, car_30sec_mean / np.max(car_30sec_mean), label='30 sec')
plt.plot(f_sup, car_1min_mean / np.max(car_1min_mean), label='1 min')
plt.plot(f_sup, car_3min_mean / np.max(car_3min_mean), label='3 min')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Normalized intenisty', fontsize = 16)
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.show()
plt.figure(figsize=(20,15))
plt.plot(f_sup, car_30sec_mean / np.max(car_30sec_mean), label='30 sec')
plt.plot(f_sup, car_1min_mean / np.max(car_1min_mean), label='1 min')
plt.plot(f_sup, car_3min_mean / np.max(car_3min_mean), label='3 min')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Normalized intenisty', fontsize = 16)
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.savefig('car_comparison_30_sec_1_min_3_min.png', dpi=600)
plt.figure(figsize=(20,15))
plt.plot(f_sup, car_30sec_mean, label='30 sec')
plt.plot(f_sup, car_1min_mean, label='1 min')
plt.plot(f_sup, car_3min_mean, label='3 min')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Normalized intenisty', fontsize = 16)
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.show()
plt.figure(figsize=(20,15))
plt.plot(f_sup, car_30sec_mean, label='30 sec')
plt.plot(f_sup, car_1min_mean, label='1 min')
plt.plot(f_sup, car_3min_mean, label='3 min')
plt.legend()
plt.title('Carbendazim with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Normalized intenisty', fontsize = 16)
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.savefig('car_comparison_not_norm.png', dpi=600)
plt.figure(figsize=(15,10))
plt.plot(f_sup, aceta_20sec_mean / np.max(aceta_20sec_mean), label='20 sec')
plt.plot(f_sup, aceta_30sec_mean / np.max(aceta_30sec_mean), label='30 sec')
plt.plot(f_sup, aceta_1min_mean / np.max(aceta_1min_mean), label='1 min')
plt.plot(f_sup, aceta_2min_mean / np.max(aceta_2min_mean), label='2 min')
plt.plot(f_sup, aceta_3min_mean / np.max(aceta_3min_mean), label='3 min')
plt.plot(f_sup, aceta_10min_mean / np.max(aceta_10min_mean), label='10 min')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Normalized intenisty', fontsize = 16)
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.show()
plt.figure(figsize=(15,10))
plt.plot(f_sup, aceta_20sec_mean / np.max(aceta_20sec_mean), label='20 sec')
plt.plot(f_sup, aceta_30sec_mean / np.max(aceta_30sec_mean), label='30 sec')
plt.plot(f_sup, aceta_1min_mean / np.max(aceta_1min_mean), label='1 min')
plt.plot(f_sup, aceta_2min_mean / np.max(aceta_2min_mean), label='2 min')
plt.plot(f_sup, aceta_3min_mean / np.max(aceta_3min_mean), label='3 min')
plt.plot(f_sup, aceta_10min_mean / np.max(aceta_10min_mean), label='10 min')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Normalized intenisty', fontsize = 16)
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.savefig('aceta_all_comparison.png', dpi = 600)
plt.figure(figsize=(15,10))
plt.plot(f_sup, aceta_30sec_mean / np.max(aceta_30sec_mean), label='30 sec')
plt.plot(f_sup, aceta_1min_mean / np.max(aceta_1min_mean), label='1 min')
plt.plot(f_sup, aceta_2min_mean / np.max(aceta_2min_mean), label='2 min')
plt.plot(f_sup, aceta_3min_mean / np.max(aceta_3min_mean), label='3 min')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Normalized intenisty', fontsize = 16)
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.show()
plt.figure(figsize=(15,10))
plt.plot(f_sup, aceta_30sec_mean / np.max(aceta_30sec_mean), label='30 sec')
plt.plot(f_sup, aceta_1min_mean / np.max(aceta_1min_mean), label='1 min')
plt.plot(f_sup, aceta_2min_mean / np.max(aceta_2min_mean), label='2 min')
plt.plot(f_sup, aceta_3min_mean / np.max(aceta_3min_mean), label='3 min')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Normalized intenisty', fontsize = 16)
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.savefig('aceta_comparison_20_sec_1_min_2_min_3_min_norm.png', dpi=600)
plt.figure(figsize=(15,10))
plt.plot(f_sup, aceta_30sec_mean, label='30 sec')
plt.plot(f_sup, aceta_1min_mean, label='1 min')
plt.plot(f_sup, aceta_2min_mean, label='2 min')
plt.plot(f_sup, aceta_3min_mean, label='3 min')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.savefig('aceta_comparison_20_sec_1_min_2_min_3_min_not_norm.png', dpi=600)
plt.figure(figsize=(15,10))
plt.plot(f_sup, aceta_30sec_mean, label='30 sec')
plt.plot(f_sup, aceta_1min_mean, label='1 min')
plt.plot(f_sup, aceta_2min_mean, label='2 min')
plt.plot(f_sup, aceta_3min_mean, label='3 min')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(fnp.arange(0, f_sup[-1], 150), ontsize=15)
plt.yticks(fontsize=15)
plt.show()
plt.figure(figsize=(15,10))
plt.plot(f_sup, aceta_30sec_mean, label='30 sec')
plt.plot(f_sup, aceta_1min_mean, label='1 min')
plt.plot(f_sup, aceta_2min_mean, label='2 min')
plt.plot(f_sup, aceta_3min_mean, label='3 min')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0, f_sup[-1], 150), ontsize=15)
plt.yticks(fontsize=15)
plt.show()
plt.figure(figsize=(15,10))
plt.plot(f_sup, aceta_30sec_mean, label='30 sec')
plt.plot(f_sup, aceta_1min_mean, label='1 min')
plt.plot(f_sup, aceta_2min_mean, label='2 min')
plt.plot(f_sup, aceta_3min_mean, label='3 min')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0, f_sup[-1], 150), ontsize=15)
plt.yticks(np.arange(0, 9000, 100)fontsize=15)
plt.show()
plt.figure(figsize=(15,10))
plt.plot(f_sup, aceta_30sec_mean, label='30 sec')
plt.plot(f_sup, aceta_1min_mean, label='1 min')
plt.plot(f_sup, aceta_2min_mean, label='2 min')
plt.plot(f_sup, aceta_3min_mean, label='3 min')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0, f_sup[-1], 150), ontsize=15)
plt.yticks(np.arange(0, 9000, 100), fontsize=15)
plt.show()
plt.figure(figsize=(15,10))
plt.plot(f_sup, aceta_30sec_mean, label='30 sec')
plt.plot(f_sup, aceta_1min_mean, label='1 min')
plt.plot(f_sup, aceta_2min_mean, label='2 min')
plt.plot(f_sup, aceta_3min_mean, label='3 min')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0, f_sup[-1], 150), fontsize=15)
plt.yticks(np.arange(0, 9000, 100), fontsize=15)
plt.show()
plt.figure(figsize=(15,10))
plt.plot(f_sup, aceta_30sec_mean, label='30 sec')
plt.plot(f_sup, aceta_1min_mean, label='1 min')
plt.plot(f_sup, aceta_2min_mean, label='2 min')
plt.plot(f_sup, aceta_3min_mean, label='3 min')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0, f_sup[-1], 150), fontsize=15)
plt.yticks(np.arange(0, 9000, 150), fontsize=15)
plt.show()
plt.figure(figsize=(15,10))
plt.plot(f_sup, aceta_30sec_mean, label='30 sec')
plt.plot(f_sup, aceta_1min_mean, label='1 min')
plt.plot(f_sup, aceta_2min_mean, label='2 min')
plt.plot(f_sup, aceta_3min_mean, label='3 min')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0, f_sup[-1], 150), fontsize=15)
plt.yticks(np.arange(0, 9000, 150), fontsize=11)
plt.show()
plt.figure(figsize=(15,10))
plt.plot(f_sup, aceta_30sec_mean, label='30 sec')
plt.plot(f_sup, aceta_1min_mean, label='1 min')
plt.plot(f_sup, aceta_2min_mean, label='2 min')
plt.plot(f_sup, aceta_3min_mean, label='3 min')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0, f_sup[-1], 150), fontsize=15)
plt.yticks(np.arange(0, 9000, 200), fontsize=11)
plt.show()
plt.figure(figsize=(15,10))
plt.plot(f_sup, aceta_20sec_mean, label='20 sec')
plt.plot(f_sup, aceta_30sec_mean, label='30 sec')
plt.plot(f_sup, aceta_1min_mean, label='1 min')
plt.plot(f_sup, aceta_2min_mean, label='2 min')
plt.plot(f_sup, aceta_3min_mean, label='3 min')
plt.plot(f_sup, aceta_10min_mean, label='10 min')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0, f_sup[-1], 150), fontsize=15)
plt.yticks(np.arange(0, 9000, 200), fontsize=11)
plt.show()
plt.figure(figsize=(15,10))
plt.plot(f_sup, aceta_20sec_mean / np,max(aceta_20sec_mean), label='20 sec')
plt.plot(f_sup, aceta_30sec_mean / np,max(aceta_30sec_mean), label='30 sec')
plt.plot(f_sup, aceta_1min_mean / np,max(aceta_1min_mean), label='1 min')
plt.plot(f_sup, aceta_2min_mean / np,max(aceta_2min_mean), label='2 min')
plt.plot(f_sup, aceta_3min_mean / np,max(aceta_3min_mean), label='3 min')
plt.plot(f_sup, aceta_10min_mean / np,max(aceta_10min_mean), label='10 min')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Intenisty', fontsize = 16)
plt.xticks(np.arange(0, f_sup[-1], 150), fontsize=15)
plt.yticks(np.arange(0, 1, 0.05), fontsize=11)
plt.show()
plt.figure(figsize=(15,10))
plt.plot(f_sup, aceta_20sec_mean / np.max(aceta_20sec_mean), label='20 sec')
plt.plot(f_sup, aceta_30sec_mean / np.max(aceta_30sec_mean), label='30 sec')
plt.plot(f_sup, aceta_1min_mean / np.max(aceta_1min_mean), label='1 min')
plt.plot(f_sup, aceta_2min_mean / np.max(aceta_2min_mean), label='2 min')
plt.plot(f_sup, aceta_3min_mean / np.max(aceta_3min_mean), label='3 min')
plt.plot(f_sup, aceta_10min_mean / np.max(aceta_10min_mean), label='10 min')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Norm Intenisty', fontsize = 16)
plt.xticks(np.arange(0, f_sup[-1], 150), fontsize=15)
plt.yticks(np.arange(0, 1, 0.05), fontsize=11)
plt.show()
plt.figure(figsize=(25,10))
plt.plot(f_sup, aceta_20sec_mean / np.max(aceta_20sec_mean), label='20 sec')
plt.plot(f_sup, aceta_30sec_mean / np.max(aceta_30sec_mean), label='30 sec')
plt.plot(f_sup, aceta_1min_mean / np.max(aceta_1min_mean), label='1 min')
plt.plot(f_sup, aceta_2min_mean / np.max(aceta_2min_mean), label='2 min')
plt.plot(f_sup, aceta_3min_mean / np.max(aceta_3min_mean), label='3 min')
plt.plot(f_sup, aceta_10min_mean / np.max(aceta_10min_mean), label='10 min')
plt.legend()
plt.title('Acetamiprid with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Norm Intenisty', fontsize = 16)
plt.xticks(np.arange(0, f_sup[-1], 150), fontsize=15)
plt.yticks(np.arange(0, 1, 0.05), fontsize=11)
plt.show()
plt.figure(figsize=(25,10))
plt.plot(f_sup, aceph_20sec_mean / np.max(aceph_20sec_mean), label='20 sec')
plt.plot(f_sup, aceph_30sec_mean / np.max(aceph_30sec_mean), label='30 sec')
plt.plot(f_sup, aceph_1min_mean / np.max(aceph_1min_mean), label='1 min')
plt.plot(f_sup, aceph_2min_mean / np.max(aceph_2min_mean), label='2 min')
plt.plot(f_sup, aceph_3min_mean / np.max(aceph_3min_mean), label='3 min')
plt.plot(f_sup, aceph_10min_mean / np.max(aceph_10min_mean), label='10 min')
plt.legend()
plt.title('Acephate with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Norm Intenisty', fontsize = 16)
plt.xticks(np.arange(0, f_sup[-1], 150), fontsize=15)
plt.yticks(np.arange(0, 1, 0.05), fontsize=11)
plt.show()
plt.figure(figsize=(25,10))
plt.plot(f_sup, aceph_20sec_mean / np.max(aceph_20sec_mean), label='20 sec')
plt.plot(f_sup, aceph_30sec_mean / np.max(aceph_30sec_mean), label='30 sec')
plt.plot(f_sup, aceph_1min_mean / np.max(aceph_1min_mean), label='1 min')
plt.plot(f_sup, aceph_2min_mean / np.max(aceph_2min_mean), label='2 min')
plt.plot(f_sup, aceph_3min_mean / np.max(aceph_3min_mean), label='3 min')
plt.plot(f_sup, aceph_10min_mean / np.max(aceph_10min_mean), label='10 min')
plt.legend()
plt.title('Acephate with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Norm Intenisty', fontsize = 16)
plt.xticks(np.arange(0, f_sup[-1], 150), fontsize=15)
plt.yticks(np.arange(0, 1, 0.05), fontsize=11)
plt.savefig('aceph_comparison_all.png', dpi=600)
plt.figure(figsize=(25,10))
plt.plot(f_sup, aceph_20sec_mean / np.max(aceph_20sec_mean), label='20 sec')
#plt.plot(f_sup, aceph_30sec_mean / np.max(aceph_30sec_mean), label='30 sec')
#plt.plot(f_sup, aceph_1min_mean / np.max(aceph_1min_mean), label='1 min')
#plt.plot(f_sup, aceph_2min_mean / np.max(aceph_2min_mean), label='2 min')
#plt.plot(f_sup, aceph_3min_mean / np.max(aceph_3min_mean), label='3 min')
#plt.plot(f_sup, aceph_10min_mean / np.max(aceph_10min_mean), label='10 min')
plt.legend()
plt.title('Acephate with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Norm Intenisty', fontsize = 16)
plt.xticks(np.arange(0, f_sup[-1], 150), fontsize=15)
plt.yticks(np.arange(0, 1, 0.05), fontsize=11)
plt.show()
plt.figure(figsize=(25,10))
#plt.plot(f_sup, aceph_20sec_mean / np.max(aceph_20sec_mean), label='20 sec')
#plt.plot(f_sup, aceph_30sec_mean / np.max(aceph_30sec_mean), label='30 sec')
plt.plot(f_sup, aceph_1min_mean / np.max(aceph_1min_mean), label='1 min')
#plt.plot(f_sup, aceph_2min_mean / np.max(aceph_2min_mean), label='2 min')
#plt.plot(f_sup, aceph_3min_mean / np.max(aceph_3min_mean), label='3 min')
#plt.plot(f_sup, aceph_10min_mean / np.max(aceph_10min_mean), label='10 min')
plt.legend()
plt.title('Acephate with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Norm Intenisty', fontsize = 16)
plt.xticks(np.arange(0, f_sup[-1], 150), fontsize=15)
plt.yticks(np.arange(0, 1, 0.05), fontsize=11)
plt.show()
plt.figure(figsize=(25,10))
#plt.plot(f_sup, aceph_20sec_mean / np.max(aceph_20sec_mean), label='20 sec')
#plt.plot(f_sup, aceph_30sec_mean / np.max(aceph_30sec_mean), label='30 sec')
#plt.plot(f_sup, aceph_1min_mean / np.max(aceph_1min_mean), label='1 min')
plt.plot(f_sup, aceph_2min_mean / np.max(aceph_2min_mean), label='2 min')
#plt.plot(f_sup, aceph_3min_mean / np.max(aceph_3min_mean), label='3 min')
#plt.plot(f_sup, aceph_10min_mean / np.max(aceph_10min_mean), label='10 min')
plt.legend()
plt.title('Acephate with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Norm Intenisty', fontsize = 16)
plt.xticks(np.arange(0, f_sup[-1], 150), fontsize=15)
plt.yticks(np.arange(0, 1, 0.05), fontsize=11)
plt.show()
plt.figure(figsize=(25,10))
#plt.plot(f_sup, aceph_20sec_mean / np.max(aceph_20sec_mean), label='20 sec')
#plt.plot(f_sup, aceph_30sec_mean / np.max(aceph_30sec_mean), label='30 sec')
#plt.plot(f_sup, aceph_1min_mean / np.max(aceph_1min_mean), label='1 min')
#plt.plot(f_sup, aceph_2min_mean / np.max(aceph_2min_mean), label='2 min')
plt.plot(f_sup, aceph_3min_mean / np.max(aceph_3min_mean), label='3 min')
#plt.plot(f_sup, aceph_10min_mean / np.max(aceph_10min_mean), label='10 min')
plt.legend()
plt.title('Acephate with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Norm Intenisty', fontsize = 16)
plt.xticks(np.arange(0, f_sup[-1], 150), fontsize=15)
plt.yticks(np.arange(0, 1, 0.05), fontsize=11)
plt.show()
plt.figure(figsize=(25,10))
#plt.plot(f_sup, aceph_20sec_mean / np.max(aceph_20sec_mean), label='20 sec')
#plt.plot(f_sup, aceph_30sec_mean / np.max(aceph_30sec_mean), label='30 sec')
#plt.plot(f_sup, aceph_1min_mean / np.max(aceph_1min_mean), label='1 min')
#plt.plot(f_sup, aceph_2min_mean / np.max(aceph_2min_mean), label='2 min')
#plt.plot(f_sup, aceph_3min_mean / np.max(aceph_3min_mean), label='3 min')
plt.plot(f_sup, aceph_10min_mean / np.max(aceph_10min_mean), label='10 min')
plt.legend()
plt.title('Acephate with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Norm Intenisty', fontsize = 16)
plt.xticks(np.arange(0, f_sup[-1], 150), fontsize=15)
plt.yticks(np.arange(0, 1, 0.05), fontsize=11)
plt.show()
plt.figure(figsize=(25,10))
#plt.plot(f_sup, aceph_20sec_mean / np.max(aceph_20sec_mean), label='20 sec')
#plt.plot(f_sup, aceph_30sec_mean / np.max(aceph_30sec_mean), label='30 sec')
#plt.plot(f_sup, aceph_1min_mean / np.max(aceph_1min_mean), label='1 min')
plt.plot(f_sup, aceph_2min_mean / np.max(aceph_2min_mean), label='2 min')
#plt.plot(f_sup, aceph_3min_mean / np.max(aceph_3min_mean), label='3 min')
#plt.plot(f_sup, aceph_10min_mean / np.max(aceph_10min_mean), label='10 min')
plt.legend()
plt.title('Acephate with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Norm Intenisty', fontsize = 16)
plt.xticks(np.arange(0, f_sup[-1], 150), fontsize=15)
plt.yticks(np.arange(0, 1, 0.05), fontsize=11)
plt.show()
plt.figure(figsize=(25,10))
#plt.plot(f_sup, aceph_20sec_mean / np.max(aceph_20sec_mean), label='20 sec')
#plt.plot(f_sup, aceph_30sec_mean / np.max(aceph_30sec_mean), label='30 sec')
plt.plot(f_sup, aceph_1min_mean / np.max(aceph_1min_mean), label='1 min')
plt.plot(f_sup, aceph_2min_mean / np.max(aceph_2min_mean), label='2 min')
#plt.plot(f_sup, aceph_3min_mean / np.max(aceph_3min_mean), label='3 min')
#plt.plot(f_sup, aceph_10min_mean / np.max(aceph_10min_mean), label='10 min')
plt.legend()
plt.title('Acephate with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Norm Intenisty', fontsize = 16)
plt.xticks(np.arange(0, f_sup[-1], 150), fontsize=15)
plt.yticks(np.arange(0, 1, 0.05), fontsize=11)
plt.show()
f_sup >= 564
np.where(f_sup >= 564)
plt.figure(figsize=(25,10))
#plt.plot(f_sup, aceph_20sec_mean / np.max(aceph_20sec_mean), label='20 sec')
#plt.plot(f_sup, aceph_30sec_mean / np.max(aceph_30sec_mean), label='30 sec')
plt.plot(f_sup, aceph_1min_mean / np.max(aceph_1min_mean), label='1 min')
plt.plot(f_sup, aceph_2min_mean / np.max(aceph_2min_mean), label='2 min')
plt.vlines(f_sup[377], ymin=0, ymax=1, linestyles='dashed')
#plt.plot(f_sup, aceph_3min_mean / np.max(aceph_3min_mean), label='3 min')
#plt.plot(f_sup, aceph_10min_mean / np.max(aceph_10min_mean), label='10 min')
plt.legend()
plt.title('Acephate with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Norm Intenisty', fontsize = 16)
plt.xticks(np.arange(0, f_sup[-1], 150), fontsize=15)
plt.yticks(np.arange(0, 1, 0.05), fontsize=11)
plt.show()
plt.figure(figsize=(25,10))
#plt.plot(f_sup, aceph_20sec_mean / np.max(aceph_20sec_mean), label='20 sec')
#plt.plot(f_sup, aceph_30sec_mean / np.max(aceph_30sec_mean), label='30 sec')
plt.plot(f_sup, aceph_1min_mean / np.max(aceph_1min_mean), label='1 min')
plt.plot(f_sup, aceph_2min_mean / np.max(aceph_2min_mean), label='2 min')
plt.vlines(f_sup[379], ymin=0, ymax=1, linestyles='dashed')
#plt.plot(f_sup, aceph_3min_mean / np.max(aceph_3min_mean), label='3 min')
#plt.plot(f_sup, aceph_10min_mean / np.max(aceph_10min_mean), label='10 min')
plt.legend()
plt.title('Acephate with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Norm Intenisty', fontsize = 16)
plt.xticks(np.arange(0, f_sup[-1], 150), fontsize=15)
plt.yticks(np.arange(0, 1, 0.05), fontsize=11)
plt.show()
plt.figure(figsize=(25,10))
#plt.plot(f_sup, aceph_20sec_mean / np.max(aceph_20sec_mean), label='20 sec')
#plt.plot(f_sup, aceph_30sec_mean / np.max(aceph_30sec_mean), label='30 sec')
plt.plot(f_sup, aceph_1min_mean / np.max(aceph_1min_mean), label='1 min')
plt.plot(f_sup, aceph_2min_mean / np.max(aceph_2min_mean), label='2 min')
plt.vlines(f_sup[381], ymin=0, ymax=1, linestyles='dashed')
#plt.plot(f_sup, aceph_3min_mean / np.max(aceph_3min_mean), label='3 min')
#plt.plot(f_sup, aceph_10min_mean / np.max(aceph_10min_mean), label='10 min')
plt.legend()
plt.title('Acephate with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Norm Intenisty', fontsize = 16)
plt.xticks(np.arange(0, f_sup[-1], 150), fontsize=15)
plt.yticks(np.arange(0, 1, 0.05), fontsize=11)
plt.show()
plt.figure(figsize=(25,10))
#plt.plot(f_sup, aceph_20sec_mean / np.max(aceph_20sec_mean), label='20 sec')
#plt.plot(f_sup, aceph_30sec_mean / np.max(aceph_30sec_mean), label='30 sec')
plt.plot(f_sup, aceph_1min_mean / np.max(aceph_1min_mean), label='1 min')
plt.plot(f_sup, aceph_2min_mean / np.max(aceph_2min_mean), label='2 min')
plt.vlines(f_sup[388], ymin=0, ymax=1, linestyles='dashed')
#plt.plot(f_sup, aceph_3min_mean / np.max(aceph_3min_mean), label='3 min')
#plt.plot(f_sup, aceph_10min_mean / np.max(aceph_10min_mean), label='10 min')
plt.legend()
plt.title('Acephate with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Norm Intenisty', fontsize = 16)
plt.xticks(np.arange(0, f_sup[-1], 150), fontsize=15)
plt.yticks(np.arange(0, 1, 0.05), fontsize=11)
plt.show()
plt.figure(figsize=(25,10))
#plt.plot(f_sup, aceph_20sec_mean / np.max(aceph_20sec_mean), label='20 sec')
#plt.plot(f_sup, aceph_30sec_mean / np.max(aceph_30sec_mean), label='30 sec')
plt.plot(f_sup, aceph_1min_mean / np.max(aceph_1min_mean), label='1 min')
plt.plot(f_sup, aceph_2min_mean / np.max(aceph_2min_mean), label='2 min')
plt.vlines(f_sup[387], ymin=0, ymax=1, linestyles='dashed')
#plt.plot(f_sup, aceph_3min_mean / np.max(aceph_3min_mean), label='3 min')
#plt.plot(f_sup, aceph_10min_mean / np.max(aceph_10min_mean), label='10 min')
plt.legend()
plt.title('Acephate with different colloidal sol.', fontsize=16)
plt.xlabel('Raman Shift', fontsize = 16)
plt.ylabel('Norm Intenisty', fontsize = 16)
plt.xticks(np.arange(0, f_sup[-1], 150), fontsize=15)
plt.yticks(np.arange(0, 1, 0.05), fontsize=11)
plt.show()
f_sup[387]
%history -f 2021_11_04_logs.py
